### ISSUE TITLE
insecure passwords

### ISSUE THREAD

**Issue by DanielRuf** [Neoflow/Neoflow-CMS#1]
SHA-1 or plaintext are completely insecure.

password_* (hash, verify, needs_rehash, ...) and password_compat are highly recommended.

Imho it would be better to use Composer and some Symfony or Laravel packages as dependencies. ;-)

PS: I miss good commit messages. It's hard to see what was done as almost all commits have no message.

**Comment by rjgamer** [comment]
Zur Zeit werden die Passwörter nur als SHA1-Hash gespeichert. Dem ist so. Ich plane aber noch ein Salt-Value miteinzubauen. Gib mir einfach noch bisschen Zeit. Das CMS ist noch in der Entwicklung und wird nirgends produktiv eingesetzt - geschweige ist es irgendwo vom Internet aus erreichbar.

Prepared Statements kommen selbstverständlich zum Zug. Aber ich denke du hast wohl nicht den Code komplett angeschaut, weil sonst wäre es dir aufgefallen. :)

Commits Message mache ich nicht, weil es sich hier um ein privates "Single-Person"-Projekt handelt.

Trotzdem: Danke für deine Hinweise. Gerade die Passwortsache wird immer gerne mal zu wenig ernst genommen.

**Comment by DanielRuf** [comment]
Bitte nicht. Auch mit einem (festen oder einfach berechenbaren Salt) ist SHA-1 unsicher bzw zu schwach. Bitte password_hash, optional mit dem bcrypt flag. Dafür gibt es auch password_compat.

Alles andere, auch selbst festgelegte Salts, sind zu unsicher.

**Comment by DanielRuf** [comment]
Du has Recht, ich konnte unterwegs mobil nicht die richtige Stelle finden. Habe die Stelle für die Parameter für die Prepared Statements (mit ?) doch gefunden. Wobei hier eben wie so oft leider wieder das Rad neu erfunden wird (Doctrine, Propel, RedBean etc, absteigend nach Empfehlung). ;-)

**Comment by rjgamer** [comment]
Vielleicht solltest du noch wissen, dass ich mit dem Neoflow CMS in erster Linie das Ziel habe ein schlankes MVC-basiertes CMS zu erstellen (Use-case technisch eine Kopie von Websitebaker). Um bloated Code zu vermeiden und zusätzlich meine PHP Skills zu steigern verzichte bewusst auf 3rd-party Frameworks und Libraries. 

Das ich mit diesem Ansatz länger brauchen werde ist mir sehr wohl bewusst. Umso mehr freut es mich natürlich von einem "Crack" wie dir Tipps und Tricks zu erhalten um so gerade die Sicherheitsrisiken zu reduzieren.

Natürlich lasse ich mich auch bei meiner Lösung von Symfony und Laravel inspirieren, aber jede Zeile im CMS habe und werde ich auch in Zukunft selber schreiben. 

Ich plane meine Commits ab dem ersten Alpha Release zu kommentieren, der hoffentlich Ende 2017 veröffentlicht werden kann.

Hier kannst du noch bisschen mehr über das Neoflow CMS in Erfahrung bringen, sofern es dich interessiert:
https://www.neoflow.ch/blog/heute-wbce-morgen-neoflow-cms

**Comment by rjgamer** [comment]
Danke nochmals herzlich für den Tipp. PHP-eigene Password-Hashing Funktionen sind implementiert. 

http://php.net/manual/de/book.password.php

**Comment by DanielRuf** [comment]
Perfekt =) :+1

Würde aber den Cost-Wert auf 10 oder besser 12 stellen, 8 sind ein paar Runden zu wenig und ist standardmäßig nicht mehr der Fall.

http://php.net/manual/de/password.constants.php
