### ISSUE TITLE
mb_strlen statt strlen

### ISSUE THREAD

**Issue by DanielRuf** [Neoflow/Neoflow-CMS#2]
https://github.com/Neoflow/Neoflow-CMS/blob/8b276271ab9e0a6a712856569acd69222f87dddc/framework/classes/Neoflow/Framework/Support/Validation/RuleTrait.php#L245

`strlen` zählt nur die Bytes was problemlos bei ASCII funktioniert. Für UTF8/Unicode bzw Multibyte-Zeichen ist das unzuverlässig, da sollte `mb_strlen` berwendet werden.

https://php.net/manual/de/function.strlen.php

https://php.net/manual/de/function.mb-strlen.php

Overloading ist in der Regel nicht aktiv und ist ab 7.2 deprecated

https://php.net/manual/de/mbstring.overload.php
Das ist eine Teil-Übersicht der mb_ Varianten

Siehe https://3v4l.org/GiblW

**Comment by rjgamer** [comment]
Ich danke dir! Nur her damit mit deinen Tipps :)

**Comment by DanielRuf** [comment]
Dazu müsste ich erstmal bei verfügbarer Zeit einen kompletten Code-Audit machen.

Wenn ich bei Walkway und Materialize und einem weiteren Projekt die aktuellen Sachen erledigt habe, kann ich das bei verfügbarer Zeit gerne machen.

Sind Pull Requests willkommen oder sind Hinweise mit Angabe der Lösungsschritte und Zeilennummern eher in deinem Interesse?

**Comment by rjgamer** [comment]
Lieber Issues mit Tipps und Angaben anstatt Pullrequest.

Aber reis dir kein Bein aus. Du machst hier ja alles freiwillig. 👍

**Comment by rjgamer** [comment]
Überall gefixt. 

Regex-based Suche via IDE `\sstr[a-z]{3,4}\(`

Ich liebe Regex :)

**Comment by DanielRuf** [comment]
> Lieber Issues mit Tipps und Angaben anstatt Pullrequest.
> 
> Aber reis dir kein Bein aus. Du machst hier ja alles freiwillig. 👍
Ach was, ich habe relativ viel freie Zeit da kein (fester) Job aktuell.
Wenn ich sehe, dass auf die Sachen wie hier eingegangen wird, dann trage ich sehr gerne was bei, was möglich ist.

> Überall gefixt.
👍
