### ISSUE TITLE
[Performance] count() in Schleifen

### ISSUE THREAD

**Issue by DanielRuf** [Neoflow/Neoflow-CMS#3]
teilweise wird `count()` in jedem Durchlauf einer Schleife ausgeführt.

Das ist sehr langsam im Vergleich zum Ansatz, das nur einmal zu berechnen und dann mit dem Wert in der Schleife zu arbeiten.

https://github.com/Neoflow/Neoflow-CMS/blob/e6cbceac069e8cf92afd32fb5504cd4424c98378/application/classes/Neoflow/CMS/Model/ThemeModel.php#L92

https://github.com/Neoflow/Neoflow-CMS/blob/e6cbceac069e8cf92afd32fb5504cd4424c98378/application/classes/Neoflow/CMS/Model/ThemeModel.php#L140

richtiger Ansatz: https://github.com/Neoflow/Neoflow-CMS/blob/c3376144f790c8ca4694da6c522764cf9c8f270e/framework/functions/normalize_post_files.php

Siehe https://3v4l.org/BRh52 und http://www.phpbench.com

**Comment by rjgamer** [comment]
Danke für den Hinweis! 👍
