### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by LimS** [Neoflow/Neoflow-CMS#44]
With install new cms on xampp
 Parse error: syntax error, unexpected ':', expecting ';' or '{' in D:\xampp\htdocs\neoflow\framework\classes\Neoflow\Framework\Handler\Loader.php on line 19

**Comment by rjgamer** [comment]
Which php version do you use? The CMS needs PHP 7 or newer...

**Comment by rjgamer** [comment]
I could reproduce your problem. You are using a PHP version lower than 7. Please switch to PHP 7 or newer. 

To prevent issues like yours I will add a version check in the next release to get a more friendly message than a parse error.

Bug closed without fix.
