### ISSUE TITLE
Fatal error getallheaders

### ISSUE THREAD

**Issue by ang3lx** [Neoflow/Neoflow-CMS#70]
Hello I've downloaded latest files (PHP=7.1)
run composer install
and open site.com/index.php

I get error
Error: Call to undefined function Neoflow\Framework\HTTP\getallheaders() on line 36

**Comment by rjgamer** [comment]
Are you using ngix? If yes, the CMS is only running with Apache.
https://github.com/Neoflow/Neoflow-CMS#requirements

But I will implement a polyfill if this is the reason.
https://github.com/Neoflow/Neoflow-CMS#requirements

**Comment by ang3lx** [comment]
I use Apache
Ok, with command
composer require ralouphie/getallheaders
works fine :)

**Comment by rjgamer** [comment]
Please download/clone the latest version of the CMS and run "composer update" to get latest release of Neoflow Framework with the "getallheaders" polyfill (if you want).

Oh and it would be really cool if you could get me a feedback about your experience with the CMS. Feel free to create a new issue with your feedback or write an email to jonathan.nessier@neoflow.ch

**Comment by ang3lx** [comment]
i've  deleted project ad run this commands again
```
git clone https://github.com/Neoflow/Neoflow-CMS.git
composer update
```

now error is
TypeError: Return value of getallheaders() must be of the type string, array returned on line 47

**Comment by rjgamer** [comment]
Again: Please download/clone the latest version of the CMS and run "composer update" to get latest release of Neoflow Framework with the "getallheaders" polyfill (if you want).

Sorry....
