### ISSUE TITLE
pages and multilang

### ISSUE THREAD

**Issue by ang3lx** [Neoflow/Neoflow-CMS#71]
Congratulations, your CMS sounds cool :)
Here some info/feedback

**1) multi language**
I think that could be useful link to switch from lang1 to lang2 inside page without return to listing, switch lang edit page (the same for articles, products and so on )
same problem with blog.
Write multilang articles is too hard

**1.2) optimize blog seo**
For SEO I think is a good idea use this construct for post url
/en/123/example-title-post-in-en
/fr/123/example-title-post-in-fr
so user can change post slug without lose google position
If user change slug from /en/123/example-title-post-in-en to /en/123/new-title-in-en
system should do - automagically 😄  -  301

**2) menu**
I use same idea of WordPress create menu (one or more that one) for each lang
and not "navigation title"

**3) code section**
I've create code section in page
`function test(){ 
	echo "code1"; 
	return "code2"; 
}
return test();`

this code print only "code2" and not echo string. Why?

sorry for all this fool ideas and for my bad english

**Comment by rjgamer** [comment]
I've created an issue for the URL history handling so you can track the current changes.
https://github.com/Neoflow/Neoflow-CMS/issues/72

**Comment by rjgamer** [comment]
#72 is planned and no conversation more than one month.
